### ISSUE TITLE
Vector Image Assets for GUI

### ISSUE THREAD

**Issue by hockeymonday** [nada-attia/dama#66]
![image](https://user-images.githubusercontent.com/58797934/115135076-8ef8e180-9fe3-11eb-9b78-c543ca7013cb.png)

**Comment by nada-attia** [comment]
thanks for assigning me an issue 🥲

**Comment by nada-attia** [comment]
https://ocaml.github.io/graphics/graphics/Graphics/index.html 
@menaattia
