### ISSUE TITLE
The Lady Pieces Can Only Jump forwards

### ISSUE THREAD

**Issue by hockeymonday** [nada-attia/dama#72]

**Comment by nada-attia** [comment]
i noticed that the lady pieces cannot make jumps if the opponents piece is directly adjacent to the lady piece (it must be at least one square apart). the bug we noticed doesn't have anything to do with the direction of the move 

@hockeymonday

**Comment by nada-attia** [comment]
`
let get_all_jumps_dir_lady sq brd clr direction =
  let vacants = get_all_vac_sq_dir [] sq clr brd direction in
  if vacants <> [] then
    get_jumps_dir (List.nth vacants 0) brd clr direction
  else get_jumps_dir sq brd clr direction
`
this fixes it

**Comment by nada-attia** [comment]
😎

**Comment by nada-attia** [comment]
😎
